targets:
  $default:
    builders:
      drift_dev:
        options:
          named_parameters: true
          databases:
            notes_database: lib/database/database.dart
          sqlite:
            modules:
              - json1
              - fts5
      slang_build_runner:
        enabled: false
      slang_build_runner:legacy:
        enabled: true
        options:
          base_locale: en
          fallback_strategy: base_locale_empty_string

          input_directory: assets/i18n
          input_file_pattern: .json
          output_directory: lib/i18n

          lazy: false
          flat_map: false

          # imports: []
          # generate_enum: false
          # contexts: {}

          obfuscation:
            enabled: false

          format:
            enabled: true
            width: 80

          timestamp: false
